spring:
  jackson:
    serialization:
      write-enums-using-to-string: true
    deserialization:
      read-enums-using-to-string: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1

grpc:
  server:
    port: 59091