spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-cart
    username: shopping-cart
    password: shopping-cart
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.datasource: DEBUG